export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',
  LOGIN = 'LOGIN',
  
  // Parking Sessions
  PARKING_SESSION_CREATED = 'PARKING_SESSION_CREATED',
  PARKING_SESSION_COMPLETED = 'PARKING_SESSION_COMPLETED',
  PARKING_SESSION_CANCELLED = 'PARKING_SESSION_CANCELLED',
  TICKET_REPRINTED = 'TICKET_REPRINTED',
  
  // Cash Management
  CASH_SHIFT_OPENED = 'CASH_SHIFT_OPENED',
  CASH_SHIFT_CLOSED = 'CASH_SHIFT_CLOSED',
  CASH_MOVEMENT_CREATED = 'CASH_MOVEMENT_CREATED',
  CASH_MOVEMENT_DELETED = 'CASH_MOVEMENT_DELETED',
  CASH_COUNT_CREATED = 'CASH_COUNT_CREATED',
  CASH_COUNT_UPDATED = 'CASH_COUNT_UPDATED',
  CASH_POLICY_CREATED = 'CASH_POLICY_CREATED',
  CASH_POLICY_UPDATED = 'CASH_POLICY_UPDATED',
  
  // Checkout
  CHECKOUT_CONFIRM = 'CHECKOUT_CONFIRM',
  SPOT_RELEASED = 'SPOT_RELEASED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_VOIDED = 'PAYMENT_VOIDED',
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_VOIDED = 'INVOICE_VOIDED',
  INVOICE_PRINTED = 'INVOICE_PRINTED',
}
